# Generated by Django 3.2.4 on 2021-12-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='User/images')),
                ('phone_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(default='+', max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Manager/images')),
                ('phone_no', models.CharField(default='+', max_length=50)),
            ],
        ),
    ]
